### ISSUE TITLE
可否加一些主子通讯、子应用间相互通讯的示例呢

### ISSUE THREAD

**Issue by meimosor** [sansui-orz/qiankun-admin#1]
可否加一些主子应用通讯、子应用间相互通讯的示例呢

**Comment by sansui-orz** [comment]
> 可否加一些主子应用通讯、子应用间相互通讯的示例呢

可以拉一下最新代码，增加了主子应用的状态共享的示例。
至于直接的事件通信就不搞了，简单的直接使用原生的DOM事件通信即可，复杂一点的可以自己实现一下事件的注册监听逻辑。
