### ISSUE TITLE
项目启动失败

### ISSUE THREAD

**Issue by liu-collab** [sansui-orz/qiankun-admin#2]
![image](https://github.com/sansui-orz/qiankun-admin/assets/63389142/d53aee2c-b701-4456-b97e-dfe7cf3f1161)

如图所示，直接npm i 后  npm run start-all 报错

**Comment by liu-collab** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\program\\nodejs\\node.exe',
1 verbose cli   'C:\\program\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start-all'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.18.0
4 verbose run-script [ 'prestart-all', 'start-all', 'poststart-all' ]
5 info lifecycle qiankun-admin@1.0.0~prestart-all: qiankun-admin@1.0.0
6 info lifecycle qiankun-admin@1.0.0~start-all: qiankun-admin@1.0.0
7 verbose lifecycle qiankun-admin@1.0.0~start-all: unsafe-perm in lifecycle true
8 verbose lifecycle qiankun-admin@1.0.0~start-all: PATH: C:\program\nvm\v14.18.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\workspace\work2\qiankun-admin\node_modules\.bin;C:\app\Git\mingw64\bin;C:\app\Git\usr\bin;C:\Users\Administrator\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\program\nvm;C:\program\nodejs;C:\app\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\ProgramData\chocolatey\bin;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\program\nvm;C:\program\nodejs;C:\app\Microsoft VS Code\bin
9 verbose lifecycle qiankun-admin@1.0.0~start-all: CWD: C:\workspace\work2\qiankun-admin
10 silly lifecycle qiankun-admin@1.0.0~start-all: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'npx concurrently "npm run start-mock" "npm run start-sub-vue" "npm run start-sub-react" "npm run start"'
10 silly lifecycle ]
11 silly lifecycle qiankun-admin@1.0.0~start-all: Returned: code: 7  signal: null
12 info lifecycle qiankun-admin@1.0.0~start-all: Failed to exec start-all script
13 verbose stack Error: qiankun-admin@1.0.0 start-all: `npx concurrently "npm run start-mock" "npm run start-sub-vue" "npm run start-sub-react" "npm run start"`
13 verbose stack Exit status 7
13 verbose stack     at EventEmitter.<anonymous> (C:\program\nvm\v14.18.0\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\program\nvm\v14.18.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid qiankun-admin@1.0.0
15 verbose cwd C:\workspace\work2\qiankun-admin
16 verbose Windows_NT 10.0.19044
17 verbose argv "C:\\program\\nodejs\\node.exe" "C:\\program\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start-all"
18 verbose node v14.18.0
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 7
22 error qiankun-admin@1.0.0 start-all: `npx concurrently "npm run start-mock" "npm run start-sub-vue" "npm run start-sub-react" "npm run start"`
22 error Exit status 7
23 error Failed at the qiankun-admin@1.0.0 start-all script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 7, true ]

**Comment by sansui-orz** [comment]
> ![image](https://user-images.githubusercontent.com/63389142/269804946-d53aee2c-b701-4456-b97e-dfe7cf3f1161.png)
> 
> 如图所示，直接npm i 后 npm run start-all 报错

额，忘记说明node版本要求了，我本地开发用的是`node v18.17.1,` `npm v8.11.0`。实际测试node v16也可以的。
可以升级之后再试试。

这里推荐[nvm](https://github.com/nvm-sh/nvm)进行node版本管理。
